version: 2

sources:
    - name: staging
      database: de-zoomcamp-artem
      schema: final_project_raw_data

      tables: 
        - name: GHG_projections_2021
        - name: GHG_projections_2019
      
models:
  - name: dbt_transform
    description: ''